name: Paystack Lite Server CI/CD

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main 

jobs:
  ci:
    name: Install & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests (Optional)
        run: npm test
        continue-on-error: true 

  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Trigger Render Deploy
        run: curl -X POST "$RENDER_DEPLOY_HOOK"
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
